#+AUTHOR: Chris Jones
#+TITLE: Collecting pokemon data
#+DATE: <2025-11-06 Thu>
#+LANGUAGE: en
#+OPTIONS: num:nil toc:nil
#+PROPERTY: header-args:python :session pokemon_data :kernel pokemon

* Introduction

This narrative covers data collection for a pokemon dataset, collecting pokedex
data alongside additional information about type strengths/weaknesses and
legendary status.

* Imports and Environmental Variables

#+begin_src python name: imports
import io
import re
from pathlib import Path

import pandas as pd
import polars as pl
import requests
from bs4 import BeautifulSoup
#+end_src

#+begin_src python name: env_vars
# dir for saving HTML files
HTML_DIR = Path("../html_files").expanduser()

# controls whether to download the pokedex table
SAVE_POKE = False
#+end_src

* Creating the Pokedex Table

** Accessing the HTML page

Here we access the main pokedex table, including basic information for all
available pokemon. We then save this table to an html file. If we are not
downloading and saving the pokedex table, then we load the existing table.

#+begin_src python
if SAVE_POKE is True:
    pokedex_url = "https://serebii.net/pokemon/nationalpokedex.shtml"
    r = requests.get(pokedex_url)
    soup = BeautifulSoup(r.content, features="html.parser")
    with open(HTML_DIR/"pokedex.html","w") as file:
        file.write(str(soup))
    print("The pokedex page has been downloaded and saved.")
else:
    with open(HTML_DIR/"pokedex.html") as file:
        soup = BeautifulSoup(file,features="html.parser")
    print("The pokedex page has been loaded.")
#+end_src

#+RESULTS:
: The pokedex page has been loaded.

** Isolating the table and converting to DataFrame

We then isolate the main table from the pokedex page. Additionally, we need to
substitute links referring to pokemon types with text in the =Type= column.
This is necessary for parsing the table and ensuring that types are filled out
correctly when converting it into a dataframe. We perform a similar operation
in the =Abilities= column, adding comma separations such that we can later
split this into multiple columns.

#+begin_src python
html_string = str(soup.find("table"))

# generate and apply substitutions for types
type_dict = {
    k: "<a>" + v
    for k, v in zip(
        re.findall('<a href="/pokemon/type/[a-z]*">', html_string),
        re.findall('(?<= href="/pokemon/type/)[a-z]*', html_string),
    )
}
for k, v in type_dict.items():
    html_string = re.sub(k, v, html_string)

# substitution inserting a comma between abilities
html_string = re.sub("</a> <br/>",",</a>",html_string)
#+end_src

We can now convert our HTML table into a DataFrame. While the data volume here
is low, we'll be using =polars= just to get some practice in.

#+begin_src python
raw_pokedex_frame = pl.from_pandas(pd.read_html(io.StringIO(html_string))[0])
#+end_src

** Rename columns and expand information

Let's inspect the head of our pokedex DataFrame

#+begin_src python
print(raw_pokedex_frame.head())
#+end_src

#+RESULTS:
#+begin_example
shape: (5, 11)
┌───────┬──────┬───────────┬──────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ 0     ┆ 1    ┆ 2         ┆ 3            ┆ … ┆ 7          ┆ 8          ┆ 9          ┆ 10         │
│ ---   ┆ ---  ┆ ---       ┆ ---          ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│ str   ┆ str  ┆ str       ┆ str          ┆   ┆ str        ┆ str        ┆ str        ┆ str        │
╞═══════╪══════╪═══════════╪══════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ No.   ┆ Pic  ┆ Name      ┆ Type         ┆ … ┆ Base Stats ┆ Base Stats ┆ Base Stats ┆ Base Stats │
│ No.   ┆ Pic  ┆ Name      ┆ Type         ┆ … ┆ Def        ┆ S.Att      ┆ S.Def      ┆ Spd        │
│ #0001 ┆ null ┆ Bulbasaur ┆ grass poison ┆ … ┆ 49         ┆ 65         ┆ 65         ┆ 45         │
│ #0002 ┆ null ┆ Ivysaur   ┆ grass poison ┆ … ┆ 63         ┆ 80         ┆ 80         ┆ 60         │
│ #0003 ┆ null ┆ Venusaur  ┆ grass poison ┆ … ┆ 83         ┆ 100        ┆ 100        ┆ 80         │
└───────┴──────┴───────────┴──────────────┴───┴────────────┴────────────┴────────────┴────────────┘
#+end_example

We still need to rename our columns, as they are currently just listed as
indexes. We also update data types appropriately, and expand type and ability
information into separate columns to account for multiple entries.

#+begin_src python
pokedex_frame = (
    raw_pokedex_frame.rename(
        lambda col: raw_pokedex_frame.select(col).row(1)[0]
    )
    .remove(pl.col("No.") == "No.")
    .drop("Pic")
)
pokedex_frame = pokedex_frame.with_columns(
    pl.col(["HP", "Att", "Def", "S.Att", "S.Def", "Spd"]).cast(int),
    pl.col("Type")
    .str.split(by=" ")
    .list.to_struct(fields=lambda idx: f"Type_{idx+1}", upper_bound=2),
    pl.col("Abilities")
    .str.split(by=",")
    .list.to_struct(fields=lambda idx: f"Abilities_{idx+1}", upper_bound=3),
).unnest(["Type","Abilities"])
print(pokedex_frame.head())
#+end_src

#+RESULTS:
#+begin_example
shape: (5, 13)
┌───────┬────────────┬────────┬────────┬───┬─────┬───────┬───────┬─────┐
│ No.   ┆ Name       ┆ Type_1 ┆ Type_2 ┆ … ┆ Def ┆ S.Att ┆ S.Def ┆ Spd │
│ ---   ┆ ---        ┆ ---    ┆ ---    ┆   ┆ --- ┆ ---   ┆ ---   ┆ --- │
│ str   ┆ str        ┆ str    ┆ str    ┆   ┆ i64 ┆ i64   ┆ i64   ┆ i64 │
╞═══════╪════════════╪════════╪════════╪═══╪═════╪═══════╪═══════╪═════╡
│ #0001 ┆ Bulbasaur  ┆ grass  ┆ poison ┆ … ┆ 49  ┆ 65    ┆ 65    ┆ 45  │
│ #0002 ┆ Ivysaur    ┆ grass  ┆ poison ┆ … ┆ 63  ┆ 80    ┆ 80    ┆ 60  │
│ #0003 ┆ Venusaur   ┆ grass  ┆ poison ┆ … ┆ 83  ┆ 100   ┆ 100   ┆ 80  │
│ #0004 ┆ Charmander ┆ fire   ┆ null   ┆ … ┆ 43  ┆ 60    ┆ 50    ┆ 65  │
│ #0005 ┆ Charmeleon ┆ fire   ┆ null   ┆ … ┆ 58  ┆ 80    ┆ 65    ┆ 80  │
└───────┴────────────┴────────┴────────┴───┴─────┴───────┴───────┴─────┘
#+end_example
