#+AUTHOR: Chris Jones
#+TITLE: Collecting pokemon data
#+DATE: <2025-11-06 Thu>
#+LANGUAGE: en
#+OPTIONS: num:nil toc:nil
#+PROPERTY: header-args:python :session pokemon_data :kernel pokemon

* Introduction

This narrative covers data collection for a pokemon dataset, collecting pokedex
data alongside additional information about type strengths/weaknesses and
legendary status.

* Imports and Environmental Variables

#+begin_src python name: imports
import io
import re
import time
from pathlib import Path

import pandas as pd
import polars as pl
import requests
from bs4 import BeautifulSoup
#+end_src

#+begin_src python name: env_vars
# dir for saving HTML files
HTML_DIR = Path("../html_files").expanduser()

# dir for saving data tables
DATA_DIR = Path("../poke_data").expanduser()

# dir for saving pokemon images
IMG_DIR = Path("../image_data").expanduser()

# controls whether to download the pokedex table
SAVE_POKE = False

# controls whether to download the type damage table
SAVE_TYPE = False

# controls whether to download pokemon sprites
SAVE_IMG = False
#+end_src

* Helper Functions

Here we define any necessary functions for repeated operations performed in
this narrative.

#+begin_src python
def type_substitution(html_string:str) -> str:
    """
    Creates a dictionary which parses links for pokemon types, and replaces
    links with type names in a string from an html file.

    :param html_string: string value taken from an html page
    :returns: string of html data where links are replaced with types
    """
    type_dict = {
        k: "<a>" + v
        for k, v in zip(
                re.findall('<a href="/pokemon/type/[a-z]*">', html_string),
                re.findall('(?<= href="/pokemon/type/)[a-z]*', html_string),
        )
    }
    for k, v in type_dict.items():
        html_string = re.sub(k, v, html_string)

    return html_string
#+end_src

* Creating the Pokedex Table

In this section, we access the main pokedex table, apply some basic
transformations and cleaning, and save the resulting DataFrame.

** Accessing the Pokedex HTML page

Here we access the main pokedex table, including basic information for all
available pokemon. We then save this table to an html file. If we are not
downloading and saving the pokedex table, then we load the existing table.

#+begin_src python
if SAVE_POKE is True:
    pokedex_url = "https://serebii.net/pokemon/nationalpokedex.shtml"
    r = requests.get(pokedex_url)
    soup = BeautifulSoup(r.content, features="html.parser")
    with open(HTML_DIR/"pokedex.html","w") as file:
        file.write(str(soup))
    print("The pokedex page has been downloaded and saved.")
else:
    with open(HTML_DIR/"pokedex.html") as file:
        soup = BeautifulSoup(file,features="html.parser")
    print("The pokedex page has been loaded.")
#+end_src

#+RESULTS:
: The pokedex page has been loaded.

** Isolating the table and converting to DataFrame

We then isolate the main table from the pokedex page. Additionally, we need to
substitute links referring to pokemon types with text in the =Type= column.
This is necessary for parsing the table and ensuring that types are filled out
correctly when converting it into a dataframe. We perform a similar operation
in the =Abilities= column, adding comma separations such that we can later
split this into multiple columns.

#+begin_src python
html_pokedex = str(soup.find("table"))

# generate and apply substitutions for types
html_pokedex = type_substitution(html_pokedex)

# substitution inserting a comma between abilities
html_pokedex = re.sub("</a> <br/>",",</a>",html_pokedex)
#+end_src

We can now convert our HTML table into a DataFrame. While the data volume here
is low, we'll be using =polars= just to get some practice in.

#+begin_src python
raw_pokedex_frame = pl.from_pandas(pd.read_html(io.StringIO(html_pokedex))[0])
#+end_src

** Rename columns and expand information

Let's inspect the head of our pokedex DataFrame

#+begin_src python
print(raw_pokedex_frame.head())
#+end_src

#+RESULTS:
#+begin_example
shape: (5, 11)
┌───────┬──────┬───────────┬──────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ 0     ┆ 1    ┆ 2         ┆ 3            ┆ … ┆ 7          ┆ 8          ┆ 9          ┆ 10         │
│ ---   ┆ ---  ┆ ---       ┆ ---          ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│ str   ┆ str  ┆ str       ┆ str          ┆   ┆ str        ┆ str        ┆ str        ┆ str        │
╞═══════╪══════╪═══════════╪══════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ No.   ┆ Pic  ┆ Name      ┆ Type         ┆ … ┆ Base Stats ┆ Base Stats ┆ Base Stats ┆ Base Stats │
│ No.   ┆ Pic  ┆ Name      ┆ Type         ┆ … ┆ Def        ┆ S.Att      ┆ S.Def      ┆ Spd        │
│ #0001 ┆ null ┆ Bulbasaur ┆ grass poison ┆ … ┆ 49         ┆ 65         ┆ 65         ┆ 45         │
│ #0002 ┆ null ┆ Ivysaur   ┆ grass poison ┆ … ┆ 63         ┆ 80         ┆ 80         ┆ 60         │
│ #0003 ┆ null ┆ Venusaur  ┆ grass poison ┆ … ┆ 83         ┆ 100        ┆ 100        ┆ 80         │
└───────┴──────┴───────────┴──────────────┴───┴────────────┴────────────┴────────────┴────────────┘
#+end_example

We still need to rename our columns, as they are currently just listed as
indexes. We also update data types appropriately, and expand type and ability
information into separate columns to account for multiple entries.

#+begin_src python
pokedex_frame = (
    raw_pokedex_frame.rename(
        lambda col: raw_pokedex_frame.select(col).row(1)[0]
    )
    .remove(pl.col("No.") == "No.")
    .drop("Pic")
)
pokedex_frame = pokedex_frame.with_columns(
    pl.col(["HP", "Att", "Def", "S.Att", "S.Def", "Spd"]).cast(int),
    pl.col("Type")
    .str.split(by=" ")
    .list.to_struct(fields=lambda idx: f"Type_{idx+1}", upper_bound=2),
    pl.col("Abilities")
    .str.split(by=",")
    .list.to_struct(fields=lambda idx: f"Abilities_{idx+1}", upper_bound=3),
).unnest(["Type","Abilities"])
print(pokedex_frame.head())
#+end_src

#+RESULTS:
#+begin_example
shape: (5, 13)
┌───────┬────────────┬────────┬────────┬───┬─────┬───────┬───────┬─────┐
│ No.   ┆ Name       ┆ Type_1 ┆ Type_2 ┆ … ┆ Def ┆ S.Att ┆ S.Def ┆ Spd │
│ ---   ┆ ---        ┆ ---    ┆ ---    ┆   ┆ --- ┆ ---   ┆ ---   ┆ --- │
│ str   ┆ str        ┆ str    ┆ str    ┆   ┆ i64 ┆ i64   ┆ i64   ┆ i64 │
╞═══════╪════════════╪════════╪════════╪═══╪═════╪═══════╪═══════╪═════╡
│ #0001 ┆ Bulbasaur  ┆ grass  ┆ poison ┆ … ┆ 49  ┆ 65    ┆ 65    ┆ 45  │
│ #0002 ┆ Ivysaur    ┆ grass  ┆ poison ┆ … ┆ 63  ┆ 80    ┆ 80    ┆ 60  │
│ #0003 ┆ Venusaur   ┆ grass  ┆ poison ┆ … ┆ 83  ┆ 100   ┆ 100   ┆ 80  │
│ #0004 ┆ Charmander ┆ fire   ┆ null   ┆ … ┆ 43  ┆ 60    ┆ 50    ┆ 65  │
│ #0005 ┆ Charmeleon ┆ fire   ┆ null   ┆ … ┆ 58  ┆ 80    ┆ 65    ┆ 80  │
└───────┴────────────┴────────┴────────┴───┴─────┴───────┴───────┴─────┘
#+end_example

With the basic pokedex DataFrame prepared, we record our data in a parquet file.

#+begin_src python
pokedex_frame.write_parquet(DATA_DIR/"pokedex.parquet")
#+end_src

* Adding additional data

While we have successfully saved our basic pokedex data, we can add additional
information for each of our pokemon. Specifically, we will add data regarding
the damage they take from/deal with different types of moves, and data
recording whether or not the pokemon is a starter or legendary.

** Accessing Type damage pages

First, we need to get a list of all available types such that we can query each
type damage page.

#+begin_src python
type_list = pl.Series(pokedex_frame.select(pl.col("Type_1").unique()))
if SAVE_TYPE is True:
    type_html_prefix = "https://serebii.net/pokemon/type/"
    for type in type_list:
        print(f"Requesting {type} page")
        r = requests.get(f"{type_html_prefix}{type}/")
        soup = BeautifulSoup(r.content, features="html.parser")
        with open(HTML_DIR / f"{type}.html", "w") as file:
            file.write(str(soup))
        # brief pause between requests to avoid being locked out
        time.sleep(5)
        print("The type pages have been downloaded and saved.")
#+end_src

Next, we open our type pages and extract information on damage taken/received.
We put damage tables into lists for damage taken and damage inflicted.

#+begin_src python
taken_tables = []
inflicted_tables = []
for type in type_list:
    with open(HTML_DIR / f"{type}.html") as file:
        soup = BeautifulSoup(file, features="html.parser")
        taken_tables.append(
            type_substitution(
                str(
                    soup.find(string=re.compile("Damage Taken")).find_parent(
                        "table"
                    )
                )
            )
        )
        inflicted_tables.append(
            type_substitution(
                str(
                    soup.find(
                        string=re.compile("Damage Inflicted")
                    ).find_parent("table")
                )
            )
        )
#+end_src

Now we can join together all of our damage taken/inflicted tables. We start
with creating a dataframe for damage taken.

#+begin_src python
taken_frame = pl.union(
    [
        pl.from_pandas(pd.read_html(io.StringIO((damage_taken)))[0])
        .transpose()
        .drop("column_0")
        .rename({"column_1": "Type", "column_2": f"Taken_by_{type}"})
        for damage_taken, type in zip(taken_tables, type_list)
    ],
    how="align",
)
print(taken_frame.head())
#+end_src

#+RESULTS:
#+begin_example
shape: (5, 19)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Type     ┆ Taken_by_ ┆ Taken_by_ ┆ Taken_by_ ┆ … ┆ Taken_by_ ┆ Taken_by_ ┆ Taken_by_ ┆ Taken_by_ │
│ ---      ┆ ice       ┆ water     ┆ normal    ┆   ┆ fairy     ┆ flying    ┆ fighting  ┆ steel     │
│ str      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│          ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ str       ┆ str       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ bug      ┆ *1        ┆ *1        ┆ *1        ┆ … ┆ *0.5      ┆ *0.5      ┆ *0.5      ┆ *0.5      │
│ dark     ┆ *1        ┆ *1        ┆ *1        ┆ … ┆ *0.5      ┆ *1        ┆ *0.5      ┆ *1        │
│ dragon   ┆ *1        ┆ *1        ┆ *1        ┆ … ┆ *0        ┆ *1        ┆ *1        ┆ *0.5      │
│ electric ┆ *1        ┆ *2        ┆ *1        ┆ … ┆ *1        ┆ *2        ┆ *1        ┆ *1        │
│ fairy    ┆ *1        ┆ *1        ┆ *1        ┆ … ┆ *1        ┆ *1        ┆ *2        ┆ *0.5      │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘
#+end_example

Next we create a dataframe for damage inflicted.

#+begin_src python
inflict_frame = pl.union(
    [
        pl.from_pandas(pd.read_html(io.StringIO((damage_inflicted)))[0])
        .transpose()
        .drop("column_0")
        .rename({"column_1": "Type", "column_2": f"Inflicted_by_{type}"})
        for damage_inflicted, type in zip(inflicted_tables, type_list)
    ],
    how="align",
)
print(inflict_frame.head())
#+end_src

#+RESULTS:
#+begin_example
shape: (5, 19)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Type     ┆ Inflicted ┆ Inflicted ┆ Inflicted ┆ … ┆ Inflicted ┆ Inflicted ┆ Inflicted ┆ Inflicted │
│ ---      ┆ _by_ice   ┆ _by_water ┆ _by_norma ┆   ┆ _by_fairy ┆ _by_flyin ┆ _by_fight ┆ _by_steel │
│ str      ┆ ---       ┆ ---       ┆ l         ┆   ┆ ---       ┆ g         ┆ ing       ┆ ---       │
│          ┆ str       ┆ str       ┆ ---       ┆   ┆ str       ┆ ---       ┆ ---       ┆ str       │
│          ┆           ┆           ┆ str       ┆   ┆           ┆ str       ┆ str       ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ bug      ┆ *1        ┆ *1        ┆ *1        ┆ … ┆ *1        ┆ *2        ┆ *0.5      ┆ *1        │
│ dark     ┆ *1        ┆ *1        ┆ *1        ┆ … ┆ *2        ┆ *1        ┆ *2        ┆ *1        │
│ dragon   ┆ *2        ┆ *0.5      ┆ *1        ┆ … ┆ *2        ┆ *1        ┆ *1        ┆ *1        │
│ electric ┆ *1        ┆ *1        ┆ *1        ┆ … ┆ *1        ┆ *0.5      ┆ *1        ┆ *0.5      │
│ fairy    ┆ *1        ┆ *1        ┆ *1        ┆ … ┆ *1        ┆ *1        ┆ *0.5      ┆ *2        │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘
#+end_example

With the damage taken and inflicted frames created, we save them to parquet
files.

#+begin_src python
taken_frame.write_parquet(DATA_DIR/"damage_taken.parquet")
inflict_frame.write_parquet(DATA_DIR/"damage_inflicted.parquet")
#+end_src

** TODO Accessing pokemon sprite data
